##setup
title: Kaiser

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
      # type: "pages"
      # type: "drafts"
    values:
      layout: "default"
      # highlighter: pygments

exclude: [Guardfile, Gemfile, Gemfile.lock, .idea]
